records/record_app/urls.py
from django.urls import path, include

from .views import *

app_name = 'record_app'
urlpatterns = [
    path("", listAuthorRecords, name="index"),
    path("search", SearchView.as_view(), name="search_results"),
    path('author/', listAuthorRecords, name="index"),
    path("keyword", listKeywordsRecords, name="index1"),
    path("title", listTitleRecords, name="index2"),
    path("about", about, name="about"),
]

records/records/urls.py
from django.contrib import admin
from django.urls import path, include

from record_app.views import *

urlpatterns = [
    path("", include('record_app.urls', namespace="records")),
    path('enerygdatabase/admin/', admin.site.urls),
    path('enerygdatabase/entry/', AddRecordsView),
    path("enerygdatabase/accounts/", include("django.contrib.auth.urls")),
    #path('records', include('record_app.urls')),
]

records/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body style="background: linear-gradient(to right, #9896F0, #FBC8D5)">
<div style="color: white; padding: 5%">
    <p style="font-size: 40px; color: deeppink"><strong>Meta Data:</strong></p>
    <p style="font-size: 30px"><strong>This site is designed using the following:</strong></p>
    <p style="font-size: 30px; color: black"><strong>Front-end / GUI: HTML, CSS, Bootstrap, Javascript</strong></p>
    <p style="font-size: 30px; color: black"><strong>Back-end / Framework: Django</strong></p>
    <p style="font-size: 30px; color: black"><strong>Scripting Language: Python</strong></p>
    <p style="font-size: 30px; color: black"><strong>Database: Mysql</strong></p>
    <p style="font-size: 30px; color: black"><strong>And was designed by Manjunath D</strong></p>
</div>
</body>
</html>

records/templates/add_records.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
            integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
            integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
            crossorigin="anonymous"></script>
</head>
<body style="font-size: 20px; background-color: #ccccff">
<div>
    <form method="post">
    Total number of records is {{ count }}
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
</div>
</body>
</html>

records/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Records</title>
</head>
<body>

</body>
</html>

records/templates/dummy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

records/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Records</title>
</head>
<style>
    .fixed-div{
        position: fixed;
   bottom: 0;
   left: 0;
   background: steelblue;
   padding: 6px;
   color: #fff;
   font-size: 1em;
    }
</style>
<script>
    function finalurl() {
    var url = new URL(window.location.href);
    var search_params = url.searchParams;
    search_params.set('ordering', document.getElementById("sort-list").value);
    url.search = search_params.toString();
    var new_url = url.toString();
    return new_url
  }
</script>
<body style="background: linear-gradient(to right, #0F3443, green); color: white">
{% include 'navbar_author.html' %}
<table>
    <tbody>
    <tr>
        <td><div class="fixed-div">
    <a style="text-decoration: none; color: white" href="http://wgbis.ces.iisc.ernet.in/energy_database/entry">Enter records</a>
</div></td>
        <td><div style="padding: 2% 12%">
    {% for instance in records %}
    {% if instance.published %}
    <p><strong>ID: </strong>{{ instance.id}} <br> <strong>Title: </strong>{{ instance.title}} <br> <strong>Author: </strong> {{instance.author}}
        <span style="margin-left: 10px"></span> <strong>Editor: </strong> {{instance.editor}}<span style="margin-left: 10px"></span>
        <strong>Year: </strong> {{instance.year}} <br>
        <strong>Publisher: </strong> {{instance.publisher}} <br>
        <strong>Source: </strong> {{instance.source}} <br>
        <strong>Reference: </strong> {{instance.reference}} <br>
        <strong>Subject: </strong> {{instance.subject}} <br>
        <strong>Keywords: </strong> {{instance.keywords}} <br>
        <strong>Abstract: </strong> {{instance.abstarct}} <br>
        <strong>Location: </strong> {{instance.loaction}} <br>
        <strong>Ref</strong> {{instance.ref}} <br>
        <strong>Ref1</strong> {{instance.ref1}}</p>
        <hr size="10" style="width: 100%; color: red">
    {% endif %}
{% endfor %}
{#{% endif %}#}

        <div class="pagination">
    <span class="step-links">
        {% if records.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ records.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ records.number }} of {{ records.paginator.num_pages }}.
        </span>

        {% if records.has_next %}
            <a class="ml-3" href="?page={{ records.next_page_number }}&q={{ query|urlencode }}">Next</a>
            <a href="/author/?q={{ query }}&?page={{ records.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


</div></td>
    </tr>
    </tbody>
</table>
</body>
</html>

records/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Records</title>
</head>
<style>
    .fixed-div{
        position: fixed;
   bottom: 0;
   left: 0;
   background: steelblue;
   padding: 6px;
   color: #fff;
   font-size: 1em;
    }
</style>
<body style="background: linear-gradient(to right, #0F3443, green); color: white">
{% include 'navbar_keywords.html' %}
<table>
    <tbody>
    <tr>
        <td><div class="fixed-div">
    <a style="text-decoration: none; color: white" href="http://wgbis.ces.iisc.ernet.in/energy_database/entry">Enter records</a>
</div></td>
        <td><div style="padding: 2% 12%">
    {% for instance in records %}
    {% if instance.published %}
    <p><strong>ID: </strong>{{ instance.id}} <br> <strong>Title: </strong>{{ instance.title}} <br> <strong>Author: </strong> {{instance.author}}
        <span style="margin-left: 10px"></span> <strong>Editor: </strong> {{instance.editor}}<span style="margin-left: 10px"></span>
        <strong>Year: </strong> {{instance.year}} <br>
        <strong>Publisher: </strong> {{instance.publisher}} <br>
        <strong>Source: </strong> {{instance.source}} <br>
        <strong>Reference: </strong> {{instance.reference}} <br>
        <strong>Subject: </strong> {{instance.subject}} <br>
        <strong>Keywords: </strong> {{instance.keywords}} <br>
        <strong>Abstract: </strong> {{instance.abstarct}} <br>
        <strong>Location: </strong> {{instance.loaction}} <br>
        <strong>Ref</strong> {{instance.ref}} <br>
        <strong>Ref1</strong> {{instance.ref1}}</p>
        <hr size="10" style="width: 100%; color: red">
    {% endif %}
{% endfor %}
{#{% endif %}#}

<div class="pagination">
    <span class="step-links">
        {% if records.has_previous %}
            <a href="/?page=1&q={{ query|urlencode }}">&laquo; first</a>
            <a href="?page={{ records.previous_page_number }}&q={{ query|urlencode }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ records.number }} of {{ records.paginator.num_pages }}.
        </span>

        {% if records.has_next %}
            <a class="ml-3" href="?page={{ records.next_page_number }}&q={{ query|urlencode }}">Next</a>
            <a href="?page={{ records.paginator.num_pages }}&q={{ query|urlencode }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div></td>
    </tr>
    </tbody>
</table>
</body>
</html>

records/templates/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Records</title>
</head>
<style>
    .fixed-div{
        position: fixed;
   bottom: 0;
   left: 0;
   background: steelblue;
   padding: 6px;
   color: #fff;
   font-size: 1em;
    }
</style>
<script>
    function finalurl() {
    var url = new URL(window.location.href);
    var search_params = url.searchParams;
    search_params.set('ordering', document.getElementById("sort-list").value);
    url.search = search_params.toString();
    var new_url = url.toString();
    return new_url
  }
</script>
<body style="background: linear-gradient(to right, #0F3443, green); color: white">
{% include 'navbar.html' %}
<table>
    <tbody>
    <tr>
        <td><div class="fixed-div">
    <a style="text-decoration: none; color: white" href="http://wgbis.ces.iisc.ernet.in/energy_database/entry">Enter records</a>
</div></td>
        <td><div style="padding: 2% 12%">
    {% for instance in records %}
    {% if instance.published %}
    <p><strong>ID: </strong>{{ instance.id}} <br> <strong>Title: </strong>{{ instance.title}} <br> <strong>Author: </strong> {{instance.author}}
        <span style="margin-left: 10px"></span> <strong>Editor: </strong> {{instance.editor}}<span style="margin-left: 10px"></span>
        <strong>Year: </strong> {{instance.year}} <br>
        <strong>Publisher: </strong> {{instance.publisher}} <br>
        <strong>Source: </strong> {{instance.source}} <br>
        <strong>Reference: </strong> {{instance.reference}} <br>
        <strong>Subject: </strong> {{instance.subject}} <br>
        <strong>Keywords: </strong> {{instance.keywords}} <br>
        <strong>Abstract: </strong> {{instance.abstarct}} <br>
        <strong>Location: </strong> {{instance.loaction}} <br>
        <strong>Ref</strong> {{instance.ref}} <br>
        <strong>Ref1</strong> {{instance.ref1}}</p>
        <hr size="10" style="width: 100%; color: red">
    {% endif %}
{% endfor %}
{#{% endif %}#}

<div class="pagination">
    <span class="step-links">
        {% if records.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ records.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ records.number }} of {{ records.paginator.num_pages }}.
        </span>

        {% if records.has_next %}
            <a class="ml-3" href="?page={{ records.next_page_number }}&q={{ query|urlencode }}">Next</a>
            <a href="/title/?q={{ query }}&?page={{ records.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div></td>
    </tr>
    </tbody>
</table>
</body>
</html>

records/templates/login.html
{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

  <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>

  {# Assumes you setup the password_reset view in your URLconf #}
  <p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

records/templates/navbar.html
{% load static %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>.dropbtn {
  background-color: #3498DB;
  color: white;
  padding: 8px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropbtn:hover, .dropbtn:focus {
  background-color: #2980B9;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  overflow: auto;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
    </style>
    <script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
</head>
<nav style="text-align: center">
    <div class="row row-cols-3" style="height: 20%; padding-top: 1%">
        <div class="col" style="width: 20%"><img src="{% static 'img/IISC_LOGO.png' %}" style="width: 150px; height: 150px"> </div>
        <div class="col"  style="width: 60%"><p style="font-size: 30px; line-height: 30px"><strong>Biodiversity, Energy & Environmental Information System</strong></p>
        <p style="font-size: 25px; line-height: 25px">Environmental Information System [ENVIS]</p>
            <p style="font-size: 18px; line-height: 10px">Center for Ecological Sciences, Indian Institute of Science, Bangalore 560012, India</p>
            <p style="font-size: 15px; line-height: 15px">&nbsp;Email: envis.ces@iisc.ac.in, tvr@iisc.ac.in &nbsp;Telephone: 080-22933099/22933503/23608661 &nbsp;<a href="{% url 'records:about' %}"><button style="padding: 1px 5px; background-color: steelblue" class="btn btn-success">meta</button></a> </p>
        </div>
        <div class="col" style="width: 20%"><img src="{% static 'img/v12_7.png' %}" style="width: 150px; height: 150px"> </div>
    </div>
          <hr size="10" style="width: 100%; color: greenyellow">

    <div style="width: 100%">
        <table align="center">
            <tbody>
            <tr>
                <td><strong>Select</strong>: Author / Keywords / <span style="color: yellow">Title</span>&nbsp;</td>
                <td>
                    <div class="dropdown">
<button style="border-radius: 5px" onclick="myFunction()" class="dropbtn btn btn-success dropdown-toggle"
                    data-toggle="dropdown">Choose</button>
    <div id="myDropdown" style="" class="dropdown-content">
      <a href="{% url 'records:index' %}">Author</a>
      <a href="{% url 'records:index1' %}">Keywords</a>
        <a href="">Title</a>
    </div>
  </div>
                </td>
                <td></td>
                <td>
                    <form action="{% url 'records:index2' %}" onchange="location = finalurl()"  method="get">
        <input name="q" id="search" type="search" placeholder="Search"
          aria-label="Search">
                        <button type="submit" style="background-color: steelblue; color:white" class="dropbtn">Search</button>
</form>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
        <div>

    </div>
</nav>

records/templates/navbar_author.html
{% load static %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>.dropbtn {
  background-color: #2eb82e;
  color: white;
  padding: 8px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropbtn:hover, .dropbtn:focus {
  background-color: #2980B9;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  overflow: auto;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
    </style>
    <script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

function finalurl() {
    var url = new URL(window.location.href);
    var search_params = url.searchParams;
    search_params.set('ordering', document.getElementById("search").value);
    url.search = search_params.toString();
    var new_url = url.toString();
    return new_url
  }


// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
</head>
<nav style="text-align: center">
    <div class="row row-cols-3" style="height: 20%; padding-top: 1%">
        <div class="col" style="width: 20%"><img src="{% static 'img/IISC_LOGO.png' %}" style="width: 150px; height: 150px"> </div>
        <div class="col"  style="width: 60%"><p style="font-size: 30px; line-height: 30px"><strong>Biodiversity, Energy & Environmental Information System</strong></p>
        <p style="font-size: 25px; line-height: 25px">Environmental Information System [ENVIS]</p>
            <p style="font-size: 18px; line-height: 10px">Center for Ecological Sciences, Indian Institute of Science, Bangalore 560012, India</p>
            <p style="font-size: 15px; line-height: 15px">&nbsp;Email: envis.ces@iisc.ac.in, tvr@iisc.ac.in &nbsp;Telephone: 080-22933099/22933503/23608661 &nbsp;<a href="{% url 'records:about' %}"><button style="padding: 1px 5px; background-color: steelblue" class="btn btn-success">meta</button></a> </p>
        </div>
        <div class="col" style="width: 20%"><img src="{% static 'img/v12_7.png' %}" style="width: 150px; height: 150px"> </div>
    </div>
    <hr size="10" style="width: 100%; color: greenyellow">
    <div style="width: 100%">
        <table align="center">
            <tbody>
            <tr>
                <td><strong>Select</strong>: <span style="color: yellow">Author</span> / Keywords / Title &nbsp;</td>
                <td>
                    <div class="dropdown">
<button style="border-radius: 5px" onclick="myFunction()" class="dropbtn btn btn-success dropdown-toggle"
                    data-toggle="dropdown">Choose</button>
    <div id="myDropdown" style="" class="dropdown-content">
      <a href="">Author</a>
      <a href="{% url 'records:index1' %}">Keywords</a>
      <a href="{% url 'records:index2' %}">Title</a>
    </div>
  </div>
                </td>
                <td></td>
                <td>
                    <form action="{% url 'records:index' %}" onchange="location = finalurl()"  method="get">
        <input name="q" id="search" type="search" placeholder="Search"
          aria-label="Search">
                        <button type="submit"  style="background-color: steelblue; color:white" class="">Search</button>
</form>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
        <div>

    </div>
</nav>

records/templates/navbar_keywords.html
{% load static %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>.dropbtn {
  background-color: #3498DB;
  color: white;
  padding: 8px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropbtn:hover, .dropbtn:focus {
  background-color: #2980B9;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  overflow: auto;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
    </style>
    <script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}


function finalurl() {
    var url = new URL(window.location.href);
    var search_params = url.searchParams;
    search_params.set('ordering', document.getElementById("search").value);
    url.search = search_params.toString();
    var new_url = url.toString();
    return new_url
  }

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
</head>
<nav style="text-align: center">
   <div class="row row-cols-3" style="height: 20%; padding-top: 1%">
        <div class="col" style="width: 20%"><img src="{% static 'img/IISC_LOGO.png' %}" style="width: 150px; height: 150px"> </div>
        <div class="col"  style="width: 60%"><p style="font-size: 30px; line-height: 30px"><strong>Biodiversity, Energy & Environmental Information System</strong></p>
        <p style="font-size: 25px; line-height: 25px">Environmental Information System [ENVIS]</p>
            <p style="font-size: 18px; line-height: 10px">Center for Ecological Sciences, Indian Institute of Science, Bangalore 560012, India</p>
            <p style="font-size: 15px; line-height: 15px">&nbsp;Email: envis.ces@iisc.ac.in, tvr@iisc.ac.in &nbsp;Telephone: 080-22933099/22933503/23608661 &nbsp;<a href="{% url 'records:about' %}"><button style="padding: 1px 5px; background-color: steelblue" class="btn btn-success">meta</button></a> </p>
        </div>
        <div class="col" style="width: 20%"><img src="{% static 'img/v12_7.png' %}" style="width: 150px; height: 150px"> </div>
    </div>
    <hr size="10" style="width: 100%; color: greenyellow">
    <div style="width: 100%">
        <table align="center">
            <tbody>
            <tr>
                <td><strong>Select</strong>: Author / <span style="color: yellow">Keywords</span> / Title &nbsp;</td>
                <td>
                    <div class="dropdown">
<button style="border-radius: 5px" onclick="myFunction()" class="dropbtn btn btn-success dropdown-toggle"
                    data-toggle="dropdown">Choose</button>
    <div id="myDropdown" style="" class="dropdown-content">
      <a href="{% url 'records:index' %}">Author</a>
        <a href="">Keywords</a>
      <a href="{% url 'records:index2' %}">Title</a>
    </div>
  </div>
                </td>
                <td></td>
                <td>
                    <form action="{% url 'records:index1' %}" onchange="location = finalurl()"  method="get">
        <input name="q" id="search" type="search" placeholder="Search"
          aria-label="Search">
                        <button type="submit" style="background-color: steelblue; color:white" class="dropbtn">Search</button>
</form>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
        <div>

    </div>
</nav>

records/templates/record_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block content %}
    <meta charset="UTF-8">
    <title>{{ object_list.title }}</title>
</head>
<body>
<p><strong>ID: </strong>{{ instance.id}} <br> <strong>Title: </strong>{{ instance.title}} <br> <strong>Author: </strong> {{instance.author}}
        <span style="margin-left: 10px"></span> <strong>Editor: </strong> {{instance.editor}}<span style="margin-left: 10px"></span>
        <strong>Year: </strong> {{instance.year}} <br>
        <strong>Publisher: </strong> {{instance.publisher}} <br>
        <strong>Source: </strong> {{instance.source}} <br>
        <strong>Reference: </strong> {{instance.reference}} <br>
        <strong>Subject: </strong> {{instance.subject}} <br>
        <strong>Keywords: </strong> {{instance.keywords}} <br>
        <strong>Abstract: </strong> {{instance.abstarct}} <br>
        <strong>Location: </strong> {{instance.loaction}} <br>
        <strong>Ref</strong> {{instance.ref}} <br>
        <strong>Ref1</strong> {{instance.ref1}}</p>
</body>
</html>

records/templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Records</title>
</head>
<body>
{% include 'navbar.html' %}
<div style="padding-left: 5%">
    <h1>Search Results</h1>

<ul>
  {% for instance in object_list %}
    <p><strong>ID: </strong>{{ instance.id}} <br> <strong>Title: </strong>{{ instance.title}} <br> <strong>Author: </strong> {{instance.author}}
        <span style="margin-left: 10px"></span> <strong>Editor: </strong> {{instance.editor}}<span style="margin-left: 10px"></span>
        <strong>Year: </strong> {{instance.year}} <br>
        <strong>Publisher: </strong> {{instance.publisher}} <br>
        <strong>Source: </strong> {{instance.source}} <br>
        <strong>Reference: </strong> {{instance.reference}} <br>
        <strong>Subject: </strong> {{instance.subject}} <br>
        <strong>Keywords: </strong> {{instance.keywords}} <br>
        <strong>Abstract: </strong> {{instance.abstarct}} <br>
        <strong>Location: </strong> {{instance.loaction}} <br>
        <strong>Ref</strong> {{instance.ref}} <br>
        <strong>Ref1</strong> {{instance.ref1}}</p>
      <hr size="10" style="width: 100%; color: red">
  {% endfor %}
</ul>
</div>
{##}
{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page=1">&laquo; first</a>#}
{#            <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">next</a>#}
{#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}
</body>
</html>